image: openjdk:11-jdk

stages:
  - preflight
  - build
  - test
  - quality
  - security

variables:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "3.22.3"
  SONAR_PROJECT_KEY: "your_project_key"
  SONAR_HOST_URL: "your_sonar_server_url"
  SONAR_LOGIN: "your_sonar_token"
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS: "7583922"

before_script:
  - apt-get update -y && apt-get install -y curl git xz-utils nodejs npm wget tar unzip lib32stdc++6 lib32z1

  # SETUP ANDROID
  - export ANDROID_HOME="$CI_PROJECT_DIR/android-home"
  - mkdir -p $ANDROID_HOME/cmdline-tools/latest
  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip $ANDROID_HOME/cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
  - mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest || true
  - export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

  # SETUP FLUTTER
  - curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
  - tar xf flutter.tar.xz
  - export PATH="$CI_PROJECT_DIR/flutter/bin:$PATH"
  - git config --global --add safe.directory $CI_PROJECT_DIR/flutter
  - flutter --version

.android_scripts: &android_scripts
  - sdkmanager --sdk_root=$ANDROID_HOME --version
  - yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
  - sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager --sdk_root=$ANDROID_HOME "platform-tools"
  - sdkmanager --sdk_root=$ANDROID_HOME "build-tools;${ANDROID_BUILD_TOOLS}"

preflight_lint:
  stage: preflight
  interruptible: true
  script:
    - flutter pub get && flutter gen-l10n
    - flutter analyze

preflight_commit_validation:
  stage: preflight
  interruptible: true
  image:
    name: node:lts
  script:
    - npm install --save-dev @commitlint/cli @commitlint/config-conventional
    - >-
      echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
    - npx commitlint --from-last-tag --to=HEAD

build:
  stage: build
  interruptible: true
  script:
    - *android_scripts
    - flutter doctor --android-licenses
    - flutter pub get && flutter gen-l10n
    - flutter build apk --debug

test:
  stage: test
  interruptible: true
  script:
    - flutter pub get && flutter gen-l10n
    - flutter test --coverage
    - genhtml coverage/lcov.info -o coverage/
  artifacts:
    paths:
      - coverage/

sonar_scan:
  stage: quality
  interruptible: true
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true

sast:
  stage: security

include:
  - template: Security/SAST.gitlab-ci.yml

